### ISSUE TITLE
Write/add decimal/binary converter

### ISSUE THREAD

**Issue by brazzy** [brazzy/floating-point-gui.de#14]
Site needs a JavaScript-based converter between decimal and binary. Needs to support fractions, of course. Ideally, it should be aware of recurring digits, show these overlined and also allow this notation in the input. Other bases would be a bonus.

**Comment by Zegnat** [comment]
Sounds like it would go far to link to [the IEEE-754 Analysis tool](https://babbage.cs.qc.cuny.edu/IEEE-754/index.xhtml) that manages to do all sorts of conversions following the standard.

There are also [old calculators](https://babbage.cs.qc.cuny.edu/IEEE-754.old/) ([dec to hex](https://babbage.cs.qc.cuny.edu/IEEE-754.old/Decimal.html), [32-bit hex to dec](https://babbage.cs.qc.cuny.edu/IEEE-754.old/32bit.html), [64-bit hex to dec](https://babbage.cs.qc.cuny.edu/IEEE-754.old/64bit.html)) that are fully JS based and could be integrated into this guide’s website (licence looks MIT/BSD style) but they are no longer supported and may contain bugs.

**Comment by brazzy** [comment]
Thank you, and sorry for  the late reply. That's a good suggestion. I had something far more fancy in mind, but got stuck very quickly and now I'm unlikely to ever find the time, so I'll add the link and call it done.
