### ISSUE TITLE
Disparity between Smallest/Largest floats and Wikipedia page

### ISSUE THREAD

**Issue by nchen24** [brazzy/floating-point-gui.de#30]
On [this](http://floating-point-gui.de/formats/fp/) page, the minimum and maximum values for floats are listed as being on the order of 10e-324 and 10e308, respectively, but the Wikipedia page (listed right above), cites the minimum being on the order of 10e-1074.  I assume this is because until 10e-324 you have full digit precision, but I feel like this should be explained or at least mentioned.

**Comment by brazzy** [comment]
Sorry for taking so long to react; you're correct and I've added a mention of subnormal numbers to the page.
