### ISSUE TITLE
Possible overflow in nearlyEqual function

### ISSUE THREAD

**Issue by ilyapopov** [brazzy/floating-point-gui.de#32]
On the page about comparison http://floating-point-gui.de/errors/comparison/

on the line 
```
    return diff / (absA + absB) < epsilon;
```
the summation can overflow, could it cause incorrect results?

**Comment by brazzy** [comment]
You're right; while floats don't overflow as easily as ints, this can happen with values near the maximum representable number. I've fixed it and added a test case.
