### ISSUE TITLE
Float comparison reference needs updating

### ISSUE THREAD

**Issue by randomascii** [brazzy/floating-point-gui.de#34]
In the references section there is a link to:
http://www.cygnus-software.com/papers/comparingfloats/comparingfloats.htm

I wrote this article many many years ago. It contains errors and has been updated. In fact, the main thing it contains is a link to the replacement, which is here:

http://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/

**Comment by brazzy** [comment]
Thanks for pointing this out, I've updated the link!
