### ISSUE TITLE
Rational numbers for money

### ISSUE THREAD

**Issue by willnwhite** [brazzy/floating-point-gui.de#35]
With big numbers, `£10/3 + £10/3 + £10/3 === £9.99...`, because `£3.33... + £3.33... + £3.33... === £9.99...`.
With rational numbers, `£10/3 + £10/3 + £10/3 === £10`.
I'm using [BigRational.js](https://github.com/peterolson/BigRational.js).

**Comment by brazzy** [comment]
It has both advantages and disadvantages compared to decimal types, and is basically a special case of symbolic math.
