### ISSUE TITLE
If floating point comparison using epsilon > the relative error, why not hardcode a value?

### ISSUE THREAD

**Issue by adam66** [brazzy/floating-point-gui.de#46]
Re floating point comparison, great solution - first real solution in the google results, but why parameterise epsilon? On that page, you hard coded it to 0.00001 twice, but then for the example utility method, you add it as a parameter.

**Comment by brazzy** [comment]
Sorry for the super late response. The reason for not hardcoding the epsilon is that the correct value can be different for different applications. Sometimes you expect values to match very closely, sometimes you need a bigger error margin.
